"""empty message

Revision ID: de8866a7edbb
Revises: 70043f702c80
Create Date: 2023-11-06 22:31:57.426392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8866a7edbb'
down_revision = '70043f702c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('token_issue_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_issue_time')
        batch_op.drop_column('token')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
